version: '2'

services:
    reverse-proxy:
        build: ./reverse-proxy
        volumes:
          - $PWD/proxy-sites/:/etc/nginx/locations/:ro
          - $PWD/proxy-servers/:/etc/nginx/conf.d/:ro
          - /etc/ssl/private/sites/:/ssl:ro
        ports:
        - "443:443"

    site:
      image: nginx:alpine
      volumes:
          - $PWD/site:/usr/share/nginx/html:ro
